// <auto-generated />
using CoreImporter.IndustrialInfo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreImporter.Migrations
{
    [DbContext(typeof(CoreImporterDbContext))]
    partial class CoreImporterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreImporter.IndustrialInfo.CurrentTurnaround", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAPACITY_OFFLINE_BBL_D");

                    b.Property<string>("PADD_REGION");

                    b.Property<string>("UNIT_TYPE_GROUP");

                    b.HasKey("Id");

                    b.ToTable("CurrentTurnarounds");
                });

            modelBuilder.Entity("CoreImporter.IndustrialInfo.LatestTurnaroundUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAPACITY_OFFLINE");

                    b.Property<string>("MARKET_REGION_NAME");

                    b.Property<string>("OUTAGE_DURATION");

                    b.Property<string>("OUTAGE_END_DATE");

                    b.Property<int>("OUTAGE_ID");

                    b.Property<string>("OUTAGE_PRECISION");

                    b.Property<string>("OUTAGE_START_DATE");

                    b.Property<string>("OUTAGE_STATUS");

                    b.Property<string>("OUTAGE_TYPE");

                    b.Property<string>("OWNER_NAME");

                    b.Property<string>("PARENTNAME");

                    b.Property<int>("PARENT_ID");

                    b.Property<string>("PHYS_CITY");

                    b.Property<string>("PHYS_POSTAL_CODE");

                    b.Property<string>("PLANT_COUNTY_NAME");

                    b.Property<int>("PLANT_ID");

                    b.Property<string>("PLANT_NAME");

                    b.Property<string>("PLANT_PHONE");

                    b.Property<string>("PLANT_STATE_NAME");

                    b.Property<string>("PREV_END_DATE");

                    b.Property<string>("PREV_START_DATE");

                    b.Property<string>("UNIT_CAPACITY");

                    b.Property<int>("UNIT_ID");

                    b.Property<string>("UNIT_NAME");

                    b.Property<string>("UNIT_STATUS");

                    b.Property<string>("UTYPE_DESC");

                    b.HasKey("Id");

                    b.ToTable("LatestTurnaroundUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
